### ISSUE TITLE
[Feature Request] Granted should support assuming profiles that are only defined in the .credentials file

### ISSUE THREAD

**Issue by JoshuaWilkes** [common-fate/granted#117]
Some of our users have reported that they use profiles which are defined only in the credentials file, rather than in config.

Currently, to use granted with these profiles they need to be added into the config file.

**Comment by TryTryAgain** [comment]
Similarly, I found that granted was very specific with how each was prepended or absent of `profile`

I ended up needing to have `[profile AssumeRole-SomeAccountID-SomeRole]` in the ~/.aws/config whereas in ~/.aws/credentials I needed to have it without "profile" `[AssumeRole-SomeAccountID-SomeRole]` otherwise it wasn't working. We also only had things stuffed into our ~/.aws/credentials file originally.
