### ISSUE TITLE
[feature request] allow specifying Firefox browser tab color for specific accounts

### ISSUE THREAD

**Issue by mikeTKOh** [common-fate/granted#156]
Generally, the ability to specify specific accounts to have a specific Firefox browser tab color.  For example, I like to have any production account tabs open in red.

Thinking about my production=red use case, would also like the ability for profiles which don't have a specified color to use any color besides red.

EDIT: I realize now that I can change the container color in the Firefox UI after the container tab has been run the first time.

**Comment by chrnorm** [comment]
@mikeTKOh would you find it useful if you could configure a color for Granted within your AWS config file, rather than changing things manually after the container is created? I am wondering if this could be useful for team members using Granted to share consistent container colors (although I suppose it is more of an individual preference)

```
[profile myProfile]
…
granted_color=red
```

**Comment by mikeTKOh** [comment]
I can't get 2 developers on the same team to do anything. :) More seriously, would be nice to able to define the color in the AWS config file, but think it would be confusing if you could also change it in the Firefox UI. Perhaps better just to leave it as it is.
