### ISSUE TITLE
[Feature Request] Store IAM user credentials in keychain

### ISSUE THREAD

**Issue by ipmb** [common-fate/granted#178]
I'd like to use granted with IAM users, but I'm not comfortable with storing my access tokens in plain text on disk (`~/.aws/credentials`) per the recommendation here https://docs.commonfate.io/granted/getting-started#set-up-your-aws-profile-file.

Would you consider a feature to store base user credentials in the keychain similar to how `aws-vault` works?

**Comment by eugene1g** [comment]
+1. This is especially useful/necessary for Mac-based developers where it's common to continuously download & run untrusted code (e.g. `node_modules` for Node.js) as the current user, so any 3rd-party code often can read `~/.aws/credentials`. This attack vector is relatively common (e.g. https://blog.sonatype.com/this-week-in-malware-npm-malware-exfiltrates-windows-sam-amazon-ec2-credentials). Presumably many people considering to use `granted` do it because they have separate work and personal accounts, and having to store work/production secrets in plaintext should be highly discouraged.

**Comment by chrnorm** [comment]
@ipmb @eugene1g we're in the final process of adding this feature! I'd love your feedback on our CLI commands, [here's a link to the docs page which adds our proposed commands](https://github.com/common-fate/docs/pull/121/files#diff-f84622185044139fa5b88575ad218cb0c50b8fc653d234932bc86a9531e65320).

```bash
 NAME:
    granted credentials - Manage secure IAM credentials
 USAGE:
    granted credentials command [command options] [arguments...]
 COMMANDS:
    add               Add IAM credentials to secure storage
    import            Import credentials from ~/.credentials file into secure storage
    update            Update existing credentials in secure storage
    list              Lists the profiles in secure storage
    clear             Remove credentials from secure storage, this also removes the associated profile entry from the AWS config file
    export-plaintext  Export credentials from the secure storage to ~/.aws/credentials file in plaintext
    help, h           Shows a list of commands or help for one command
 OPTIONS:
    --help, -h  show help (default: false)
 ```

**Comment by ipmb** [comment]
Awesome, this looks great! My only nitpick is that something like `remove` or `delete` is more intuitive (opposite of `add`) to me than `clear`.

`aws-vault` also provides a `rotate` command which is super handy, but more of a nice-to-have. It's like `update`, but it also takes care of generating the new keys at AWS.

**Comment by eugene1g** [comment]
@chrnorm This is excellent. The only concern that I have is about this workflow - 

1. I have an existing "hardcoded" AWS setup, with `~/.aws/config` and `~/.aws/credentials`
2. I run `granted credentials import`
3. I play around with `granted` and decide not to use it, or use it for a subset of profiles so I want to reset its storage after 10 minutes.
4. I run `granted credentials clear`
5. Concern: granted will clear `~/.aws/config` and delete my original "hardcoded" setup

If this is the case, it's could be quite a footgun because it will be difficult for me to recreate that hardcoded setup if I had that file for a while. I suppose the current solution will be to ensure I run `granted credentials export-plaintext`, so maybe the `...credentials clear` should execute in dry-run mode by default and have a `--force` flag before it actually overrides the static config.

**Comment by chrnorm** [comment]
@eugene1g @ipmb thanks for your feedback! This feature has been merged and will be included in the next Granted release.

We changed the `clear` command to be `remove`.

@eugene1g regarding your concerns, we've added some warnings to prompt the user to run `granted credentials export-plaintext` prior to running `granted credentials clear`. I'd be very open to additional feedback and improvement suggestions around this after the new release is shipped. I have tested a prerelease build of this and found that Granted would correctly restore `~/.aws/config` entries after running `granted credentials export-plaintext`

**Comment by eugene1g** [comment]
@chrnorm I had to set up `granted` on a new computer today and went through the process of installing it and adding credentials end-to-end on a clean setup - everything worked very well for multiple AWS accounts and local browsers. Thank you!
