### ISSUE TITLE
Document how `granted sso populate` works

### ISSUE THREAD

**Issue by chrnorm** [common-fate/granted#271]
We need to add instructions on how to use this to our docs.

**Comment by benfreke** [comment]
Not an issue, but worth mentioning. 

One of the parameters is `region`, which will set the `sso_region` key in the config. 

But I discovered today (I'm not a power user of AWS), that when I ran an `aws ecs` task that the `region` being used appears to be defaulting to the `sso_region`. 

Because my tasks are running in a different region to the `sso_region`, my task was failing to find the ecs cluster I knew existed.

I would suggest a comment mentioning that you will need to manually add the `region` key to your aws config generated by this command, if you don't add it manually to your cli commands. For me, because my accounts are segregated by region, it makes sense to add this into my config. For others, who use the region on the cli command it won't make sense. 

I also think it would be a good idea to change the `--region` flag to be `--sso_region` to reflect how it will be used in the generated config. That's a breaking change of course, so that's more of hey it'd be good if in the future it changes. 

Awesome project btw, very very handy.
