### ISSUE TITLE
Docs root page is "Page Not found"

### ISSUE THREAD

**Issue by connorads** [common-fate/granted#51]
https://docs.commonfate.io/
![image](https://user-images.githubusercontent.com/10026538/155554971-0e1fcc86-3a59-402f-b314-56b4b0cafabb.png)

The `Common Fate` logo also links here https://docs.commonfate.io/
![image](https://user-images.githubusercontent.com/10026538/155555224-4dabc238-2179-4b6a-b9d1-6ae9c3bdcd5a.png)

I couldn't find the repo for the docs, is that also open source?

**Comment by meyerjrr** [comment]
Hey @connorads!
Thanks for opening this issue. Could I get you to confirm if you're still not finding the docs page? I could not replicate the issue.

**Comment by chrnorm** [comment]
@meyerjrr I was able to replicate this so can offer some steps!

1. Visit https://docs.commonfate.io/granted/introduction
2. Click the Common Fate logo from this page. Because it’s a client-side redirect in Docusaurus, you are taken to the index page which doesn’t exist and 404s:

@connorads our docs aren’t yet open sourced but this is something we definitely should do! I’ll post a link on this issue once the repo is published, would very much welcome any contributions to documentation.

We had a server side redirect set up in our static hosting provider to redirect docs.commonfate.io to https://docs.commonfate.io/granted/introduction, however this redirect is happening client side. Thanks again for raising the issue as we didn’t catch this prior to releasing the site.
