### ISSUE TITLE
Feature Request: Support use on "headless" nodes

### ISSUE THREAD

**Issue by QuinnyPig** [common-fate/granted#78]
Granted bombs out on initial run on Linux if xdg-settings isn't installed. A usage model where it spits out the URL for the console to STDOUT is normally how I've seen other SSO-driven tools handle this; is there a plan to support that approach?

**Comment by meyerjrr** [comment]
Hey @QuinnyPig! 
Thanks for the suggestion, definitely worth having the url passed to the user approach. I just want to get to the bottom of the error you received when trying in your headless node.
1. Were you able to retrieve the credentials using Granted -> errored out attempting to open the browser?
2. Were you unable to get the creds due to not being able to run a sso console device flow? 
I think the error message you received will indicate which of these occurred

**Comment by QuinnyPig** [comment]
Just noticed it was version 0.1.3, if that's relevant; installed via following the instructions in the quickstart.

`assume` bombs out with:

 ```
Granted works best with Firefox but also supports Chrome, Brave, and Edge (https://granted.dev/browsers).
exec: "xdg-settings": executable file not found in $PATH

```

**Comment by meyerjrr** [comment]
Ahh it's falling over when attempting to find your default browser on linux. Thanks for the added info! 
Should probably silently error here and let the user specify their browsers path

**Comment by QuinnyPig** [comment]
I’d also request that STDOUT be one of the browser options.
